name: Deploy to Netlify

on:
  push:
    branches:
      - main # ajuste para a branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      - name: Instalar dependências e construir o aplicativo
        run: |
          yarn
          tsc && vite build

      - name: Deploy para Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          command: deploy
          args: --prod
        env:
          NETLIFY_SITE_ID: d64669d9-352b-4a28-9165-1177d16ae9bd

          # Substitua pelo ID do seu site Netlify
