name: Deploy to Netlify

on:
  push:
    branches:
      - main # ajuste para a branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      - name: Instalar dependências e construir o aplicativo
        run: |
          yarn
          yarn build

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: ${{ runner.os }}-build-prod-${{ hashFiles('**/yarn.lock') }}

      - name: Deploy para Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          command: deploy
          args: --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
